### PR TITLE
Day 3

### PR DESCRIPTION
**Pull request by timothykou**

### CODE REVIEW

**Comment by ghost** [comment]
I'm gonna have to work through day 3... 🙃

**Comment by timothykou** [comment]
Did it not work for you?

**Comment by ghost** [comment]
I didn't test it yet, I'm sure it works I'm just not sure what I'm looking at logic wise

**Comment by ghost** [comment]
They both worked 💥

**Review by ghost — APPROVED** [review]

**Comment by timothykou** [comment]
@carkmorwin the logic is sort of wacko

**Pull request merged**
